name       : tarsnap
version    : 1.0.39
release    : 1
source     :
  - https://www.tarsnap.com/download/tarsnap-autoconf-1.0.39.tgz : 5613218b2a1060c730b6c4a14c2b34ce33898dd19b38fb9ea0858c5517e42082
license    : Distributable
component  : network.clients
optimize   : lto
summary    : Tarsnap is a secure, efficient online backup service.
description: |
    A simple command line tool for making cloud backups on the tarsnap cloud service.
builddeps  :
  - pkgconfig(ext2fs)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
    install -D -d -m 00755 $installdir/usr/share/defaults
    mv $installdir/etc $installdir/usr/share/defaults/tarsnap
